Metrics/LineLength:
  Max: 100
Documentation:
  Enabled: false
NumericLiterals:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
SingleLineBlockParams:
  Enabled: false
FrozenStringLiteralComment:
  Enabled: false
MutableConstant:
  Enabled: false
MultilineMethodCallIndentation:
  EnforcedStyle: indented
